# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-03 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_advert'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='Advert_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
