# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-23 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='postdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
