# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-03 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190503_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
