# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-03 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_star_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('about', models.TextField(blank=True, default='no information')),
            ],
            options={
                'verbose_name': 'director',
                'verbose_name_plural': 'directors',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='director',
            field=models.ManyToManyField(default='none', to='articles.Director'),
        ),
    ]
