# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-05 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20190504_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='classic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='editorspick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='in_cinema',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='poster',
            field=models.ImageField(blank=True, default='defaultposter.png', upload_to=''),
        ),
    ]
