# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-23 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_remove_article_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
