# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-08 10:19
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_article_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='no information'),
        ),
    ]
