# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-12 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_delete_daff'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Post_status',
            field=models.CharField(choices=[('block', 'Block'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
