# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-12 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_comment_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Post_status',
            new_name='comment_status',
        ),
    ]
