# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-12 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20190512_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_status',
        ),
    ]
