# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-12 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_remove_comment_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_status',
            field=models.BooleanField(default=False),
        ),
    ]
