# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-26 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_comment_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, default='no information'),
        ),
    ]
