# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-28 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_auto_20190526_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='poster',
            field=models.ImageField(blank=True, default='defaultposter.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='star',
            name='poster',
            field=models.ImageField(blank=True, default='defaultposter.png', upload_to=''),
        ),
    ]
