# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-28 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_auto_20190528_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='poster',
            field=models.ImageField(blank=True, default='defaultstar.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='star',
            name='poster',
            field=models.ImageField(blank=True, default='defaultstar.png', upload_to=''),
        ),
    ]
