# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-28 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_auto_20190528_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
