# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-01-18 12:34
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_article_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='classic',
        ),
        migrations.RemoveField(
            model_name='article',
            name='director',
        ),
        migrations.RemoveField(
            model_name='article',
            name='editorspick',
        ),
        migrations.RemoveField(
            model_name='article',
            name='in_cinema',
        ),
        migrations.RemoveField(
            model_name='article',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='article',
            name='star',
        ),
        migrations.AlterField(
            model_name='article',
            name='postdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='no information'),
        ),
    ]
